# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch and changes in folder src-python
name: Test-Pull-Request
on:
  push:
    branches:
      - master
    paths:
      - src-python
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

# Run the tests
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: ./src-python

    steps:
      # Checks out the repository
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install package locally
      - name: Install package
        run: pip install -e .
        with:
          python-version: ${{ matrix.python-version }}

      # Install dev dependencies
      - name: Install dependencies
        run: pip install -r ./extras/dev.txt
        with:
          python-version: ${{ matrix.python-version }}

      # Run tests
      - name: Test
        run: pytest
        with:
          python-version: ${{ matrix.python-version }}
